export const initialPersonnelData = [
  {
    id: 'NV001',
    accountEmail: 'an.nguyen@namdogroup.vn',
    license: 'Đầy đủ chức năng',
    role: 'Quản trị viên',
    lastName: 'Nguyễn Văn',
    firstName: 'An',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành', position: 'Giám đốc', rank: 1 }
    ],
    personalEmail: 'an.nguyen85@gmail.com',
    phone: '0901234567',
    dob: '1985-05-15',
    gender: 'Nam',
    workEmail: 'an.nguyen@namdogroup.vn',
    address: 'Hà Nội, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Chính thức',
    startDate: '2020-01-01',
    grossSalary: 50000000,
    tax: 10,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV002',
    accountEmail: 'bich.tran@namdogroup.vn',
    license: 'Giới hạn',
    role: 'Nhân viên',
    lastName: 'Trần Thị',
    firstName: 'Bích',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / Marketing', position: 'Trưởng phòng Marketing', rank: 2 }
    ],
    personalEmail: 'bich.tran@gmail.com',
    phone: '0912345678',
    dob: '1990-08-20',
    gender: 'Nữ',
    workEmail: 'bich.tran@namdogroup.vn',
    address: 'Đà Nẵng, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Chính thức',
    startDate: '2021-03-15',
    grossSalary: 25000000,
    tax: 5,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV003',
    accountEmail: 'cuong.le@namdogroup.vn',
    license: 'Đầy đủ chức năng',
    role: 'Nhân viên',
    lastName: 'Lê Hoàng',
    firstName: 'Cường',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / QA/QC', position: 'Trưởng bộ phận QA/QC', rank: 2 }
    ],
    personalEmail: 'cuong.le@gmail.com',
    phone: '0987654321',
    dob: '1988-11-10',
    gender: 'Nam',
    workEmail: 'cuong.le@namdogroup.vn',
    address: 'Hồ Chí Minh, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Chính thức',
    startDate: '2019-06-01',
    grossSalary: 30000000,
    tax: 10,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV004',
    accountEmail: 'dung.pham@namdogroup.vn',
    license: 'Chỉ xem',
    role: 'Nhân viên',
    lastName: 'Phạm Thị',
    firstName: 'Dung',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / QA/QC', position: 'Nhân viên QA/QC', rank: 3 }
    ],
    personalEmail: 'dung.pham@gmail.com',
    phone: '0971234567',
    dob: '1995-02-25',
    gender: 'Nữ',
    workEmail: 'dung.pham@namdogroup.vn',
    address: 'Hải Phòng, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Thử việc',
    startDate: '2023-01-10',
    grossSalary: 12000000,
    tax: 0,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV005',
    accountEmail: 'em.hoang@namdogroup.vn',
    license: 'Giới hạn',
    role: 'Nhân viên',
    lastName: 'Hoàng Văn',
    firstName: 'Em',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / Thu mua', position: 'Nhân viên Thu mua', rank: 3 }
    ],
    personalEmail: 'em.hoang@gmail.com',
    phone: '0969876543',
    dob: '1992-07-12',
    gender: 'Nam',
    workEmail: 'em.hoang@namdogroup.vn',
    address: 'Cần Thơ, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Chính thức',
    startDate: '2022-09-01',
    grossSalary: 15000000,
    tax: 5,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV006',
    accountEmail: 'phuong.dang@namdogroup.vn',
    license: 'Giới hạn',
    role: 'Nhân viên',
    lastName: 'Đặng Thu',
    firstName: 'Phương',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / Thu mua', position: 'Trưởng bộ phận Thu mua', rank: 2 }
    ],
    personalEmail: 'phuong.dang@gmail.com',
    phone: '0933456789',
    dob: '1989-12-05',
    gender: 'Nữ',
    workEmail: 'phuong.dang@namdogroup.vn',
    address: 'Hà Nội, Việt Nam',
    workStatus: 'Nghỉ thai sản',
    type: 'Chính thức',
    startDate: '2020-04-15',
    grossSalary: 28000000,
    tax: 5,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV007',
    accountEmail: 'hung.bui@namdogroup.vn',
    license: 'Đầy đủ chức năng',
    role: 'Quản lý',
    lastName: 'Bùi Văn',
    firstName: 'Hùng',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / Công nghệ thông tin', position: 'Kỹ sư trưởng', rank: 2 }
    ],
    personalEmail: 'hung.bui@gmail.com',
    phone: '0945678901',
    dob: '1987-03-30',
    gender: 'Nam',
    workEmail: 'hung.bui@namdogroup.vn',
    address: 'Đà Nẵng, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Chính thức',
    startDate: '2018-11-20',
    grossSalary: 40000000,
    tax: 10,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV008',
    accountEmail: 'yen.ngo@namdogroup.vn',
    license: 'Giới hạn',
    role: 'Nhân viên',
    lastName: 'Ngô Thị',
    firstName: 'Yến',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / Công nghệ thông tin', position: 'Kỹ thuật viên', rank: 3 }
    ],
    personalEmail: 'yen.ngo@gmail.com',
    phone: '0919876543',
    dob: '1996-09-18',
    gender: 'Nữ',
    workEmail: 'yen.ngo@namdogroup.vn',
    address: 'Hồ Chí Minh, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Thử việc',
    startDate: '2023-05-01',
    grossSalary: 14000000,
    tax: 0,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV009',
    accountEmail: 'duy.vu@namdogroup.vn',
    license: 'Đầy đủ chức năng',
    role: 'Quản lý',
    lastName: 'Vũ Đức',
    firstName: 'Duy',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / Tài chính - Kế toán', position: 'Kế toán trưởng', rank: 2 }
    ],
    personalEmail: 'duy.vu@gmail.com',
    phone: '0981122334',
    dob: '1983-04-22',
    gender: 'Nam',
    workEmail: 'duy.vu@namdogroup.vn',
    address: 'Hà Nội, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Chính thức',
    startDate: '2015-08-10',
    grossSalary: 35000000,
    tax: 10,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  },
  {
    id: 'NV010',
    accountEmail: 'nhu.doan@namdogroup.vn',
    license: 'Giới hạn',
    role: 'Nhân viên',
    lastName: 'Đoàn Quỳnh',
    firstName: 'Như',
    assignments: [
      { department: 'Hội đồng quản trị / Ban Giám đốc điều hành / Nhân sự', position: 'Chuyên viên Nhân sự', rank: 3 }
    ],
    personalEmail: 'nhu.doan@gmail.com',
    phone: '0909988776',
    dob: '1994-10-08',
    gender: 'Nữ',
    workEmail: 'nhu.doan@namdogroup.vn',
    address: 'Hồ Chí Minh, Việt Nam',
    workStatus: 'Đang làm việc',
    type: 'Chính thức',
    startDate: '2021-02-20',
    grossSalary: 18000000,
    tax: 5,
    socialInsurance: 8,
    unemploymentInsurance: 1,
    healthInsurance: 1.5
  }
];
