// Automatically generated from truy_xuat_nguon_goc.db. Do not edit directly.

export const traceabilityData = [
  {
    "id": "BG-001",
    "ma_puc": "BG-PUC-0001",
    "dia_chi_vuon": "Xã Tân Hương, H. Yên Phong, Bắc Giang",
    "ten_vuon": "Vườn Anh Minh",
    "ngay_thu_hoach": "2026-06-05",
    "lan_phun_thuoc_gan_nhat": "2026-05-28",
    "cach_ly": null,
    "loai": null,
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "BG-002",
    "ma_puc": "BG-PUC-0002",
    "dia_chi_vuon": "Xã Quang Châu, H. Việt Yên, Bắc Giang",
    "ten_vuon": "Vườn Chị Lan",
    "ngay_thu_hoach": "2026-06-06",
    "lan_phun_thuoc_gan_nhat": "2026-05-30",
    "cach_ly": "Không",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 17.2,
    "khoi_luong_dong_goi": 15.7,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": "VN-PHC-0009",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "HG-001",
    "ma_puc": "HG-PUC-0001",
    "dia_chi_vuon": "Xã Bình Long, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Bác Tám",
    "ngay_thu_hoach": "2026-06-04",
    "lan_phun_thuoc_gan_nhat": "2026-05-27",
    "cach_ly": "Có",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 24.1,
    "khoi_luong_dong_goi": 23.9,
    "noi_xuat_khau": "Hàn Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Á Đông",
    "ma_phc": "VN-PHC-0010",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "HG-002",
    "ma_puc": "HG-PUC-0002",
    "dia_chi_vuon": "Xã Vĩnh Thạnh Trung, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Chú Hai",
    "ngay_thu_hoach": "2026-06-07",
    "lan_phun_thuoc_gan_nhat": "2026-06-01",
    "cach_ly": null,
    "loai": null,
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "TG-001",
    "ma_puc": "TG-PUC-0001",
    "dia_chi_vuon": "Xã Long Trung, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Anh Hùng",
    "ngay_thu_hoach": "2026-06-03",
    "lan_phun_thuoc_gan_nhat": "2026-05-26",
    "cach_ly": "Có",
    "loai": null,
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "TG-002",
    "ma_puc": "TG-PUC-0002",
    "dia_chi_vuon": "Xã Tam Bình, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Bà Năm",
    "ngay_thu_hoach": "2026-06-08",
    "lan_phun_thuoc_gan_nhat": "2026-06-02",
    "cach_ly": "Không",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 9.8,
    "khoi_luong_dong_goi": 9.1,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Thanh Bình",
    "ma_phc": "VN-PHC-0002",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "BG-003",
    "ma_puc": "BG-PUC-0003",
    "dia_chi_vuon": "Xã Hương Mai, H. Việt Yên, Bắc Giang",
    "ten_vuon": "Vườn Anh Tuấn",
    "ngay_thu_hoach": "2026-06-05",
    "lan_phun_thuoc_gan_nhat": "2026-05-29",
    "cach_ly": "Không",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 6.7,
    "khoi_luong_dong_goi": 6.4,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": "VN-PHC-0009",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "LA-001",
    "ma_puc": "LA-PUC-0001",
    "dia_chi_vuon": "Xã Định Thành, H. Đức Hòa, Long An",
    "ten_vuon": "Vườn Chị Thu",
    "ngay_thu_hoach": "2026-06-06",
    "lan_phun_thuoc_gan_nhat": "2026-05-31",
    "cach_ly": null,
    "loai": null,
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "LA-002",
    "ma_puc": "LA-PUC-0002",
    "dia_chi_vuon": "Xã Tân Mỹ, H. Đức Hòa, Long An",
    "ten_vuon": "Vườn Ông Sáu",
    "ngay_thu_hoach": "2026-06-07",
    "lan_phun_thuoc_gan_nhat": "2026-06-01",
    "cach_ly": "Có",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 20.3,
    "khoi_luong_dong_goi": 18.5,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": "VN-PHC-0009",
    "ket_qua_kiem_dich": "Không đạt"
  },
  {
    "id": "HG-003",
    "ma_puc": "HG-PUC-0003",
    "dia_chi_vuon": "Xã Bình Mỹ, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Cô Ba",
    "ngay_thu_hoach": "2026-06-04",
    "lan_phun_thuoc_gan_nhat": "2026-05-28",
    "cach_ly": "Có",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 8.3,
    "khoi_luong_dong_goi": 7.9,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Rồng Việt",
    "ma_phc": "VN-PHC-0004",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "TG-003",
    "ma_puc": "TG-PUC-0003",
    "dia_chi_vuon": "Xã Mỹ Long, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Anh Phước",
    "ngay_thu_hoach": "2026-06-09",
    "lan_phun_thuoc_gan_nhat": "2026-06-03",
    "cach_ly": "Không",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 23.6,
    "khoi_luong_dong_goi": 23,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói VinaGreen",
    "ma_phc": "VN-PHC-0005",
    "ket_qua_kiem_dich": "Không đạt"
  },
  {
    "id": "BG-004",
    "ma_puc": "BG-PUC-0004",
    "dia_chi_vuon": "Xã Nội Hoàng, H. Yên Dũng, Bắc Giang",
    "ten_vuon": "Vườn Chị Hoa",
    "ngay_thu_hoach": "2026-06-05",
    "lan_phun_thuoc_gan_nhat": "2026-05-30",
    "cach_ly": "Không",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 13,
    "khoi_luong_dong_goi": 12.6,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": "VN-PHC-0009",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "VL-001",
    "ma_puc": "VL-PUC-0001",
    "dia_chi_vuon": "Xã Trung Thành, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Bác Bảy",
    "ngay_thu_hoach": "2026-06-06",
    "lan_phun_thuoc_gan_nhat": "2026-05-29",
    "cach_ly": "Có",
    "loai": "Trái tươi xuất khẩu",
    "khoi_luong_lo_hang": 14,
    "khoi_luong_dong_goi": 12.9,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hưng Phát",
    "ma_phc": "VN-PHC-0001",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "VL-002",
    "ma_puc": "VL-PUC-0002",
    "dia_chi_vuon": "Xã Hiếu Phụng, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Chú Chín",
    "ngay_thu_hoach": "2026-06-07",
    "lan_phun_thuoc_gan_nhat": "2026-06-02",
    "cach_ly": "Có",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 16.8,
    "khoi_luong_dong_goi": 15.5,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Thanh Bình",
    "ma_phc": "VN-PHC-0002",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "LA-003",
    "ma_puc": "LA-PUC-0003",
    "dia_chi_vuon": "Xã Nhị Thành, H. Thủ Thừa, Long An",
    "ten_vuon": "Vườn Anh Khoa",
    "ngay_thu_hoach": "2026-06-08",
    "lan_phun_thuoc_gan_nhat": "2026-06-01",
    "cach_ly": "Không",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 19.2,
    "khoi_luong_dong_goi": 17.4,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hưng Phát",
    "ma_phc": "VN-PHC-0001",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "TG-004",
    "ma_puc": "TG-PUC-0004",
    "dia_chi_vuon": "Xã Phú Nhuận, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Bà Tư",
    "ngay_thu_hoach": "2026-06-04",
    "lan_phun_thuoc_gan_nhat": "2026-05-27",
    "cach_ly": null,
    "loai": null,
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "HG-004",
    "ma_puc": "HG-PUC-0004",
    "dia_chi_vuon": "Xã Khánh Hòa, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Ông Hai",
    "ngay_thu_hoach": "2026-06-09",
    "lan_phun_thuoc_gan_nhat": "2026-06-03",
    "cach_ly": "Có",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 22.2,
    "khoi_luong_dong_goi": 20.1,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Minh Sáng",
    "ma_phc": "VN-PHC-0008",
    "ket_qua_kiem_dich": "Không đạt"
  },
  {
    "id": "BG-005",
    "ma_puc": "BG-PUC-0005",
    "dia_chi_vuon": "Xã Tự Lạn, H. Việt Yên, Bắc Giang",
    "ten_vuon": "Vườn Chị Ngọc",
    "ngay_thu_hoach": "2026-06-10",
    "lan_phun_thuoc_gan_nhat": "2026-06-04",
    "cach_ly": "Không",
    "loai": "Trái tươi xuất khẩu",
    "khoi_luong_lo_hang": 9.3,
    "khoi_luong_dong_goi": 8.5,
    "noi_xuat_khau": "Hàn Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Á Đông",
    "ma_phc": "VN-PHC-0010",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "VL-003",
    "ma_puc": "VL-PUC-0003",
    "dia_chi_vuon": "Xã Quới An, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Anh Dũng",
    "ngay_thu_hoach": "2026-06-06",
    "lan_phun_thuoc_gan_nhat": "2026-05-30",
    "cach_ly": null,
    "loai": null,
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "LA-004",
    "ma_puc": "LA-PUC-0004",
    "dia_chi_vuon": "Xã Long Thượng, H. Cần Giuộc, Long An",
    "ten_vuon": "Vườn Bác Ba",
    "ngay_thu_hoach": "2026-06-07",
    "lan_phun_thuoc_gan_nhat": "2026-05-31",
    "cach_ly": "Không",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 16.5,
    "khoi_luong_dong_goi": 15.3,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hòa Phát",
    "ma_phc": "VN-PHC-0007",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "BG-006",
    "ma_puc": "BG-PUC-0006",
    "dia_chi_vuon": "Xã Lương Phong, H. Hiệp Hòa, Bắc Giang",
    "ten_vuon": "Vườn Chú Sơn",
    "ngay_thu_hoach": "2026-06-20",
    "lan_phun_thuoc_gan_nhat": "2026-06-13",
    "cach_ly": "Có",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 8.8,
    "khoi_luong_dong_goi": 8,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hòa Phát",
    "ma_phc": "VN-PHC-0007",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "BG-007",
    "ma_puc": "BG-PUC-0007",
    "dia_chi_vuon": "Xã Mỹ Hà, H. Lạng Giang, Bắc Giang",
    "ten_vuon": "Vườn Anh Dũng",
    "ngay_thu_hoach": "2026-06-22",
    "lan_phun_thuoc_gan_nhat": "2026-06-15",
    "cach_ly": "Không",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 13.2,
    "khoi_luong_dong_goi": 13,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Thanh Bình",
    "ma_phc": "VN-PHC-0002",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "BG-008",
    "ma_puc": "BG-PUC-0008",
    "dia_chi_vuon": "Xã Hồng Giang, H. Lục Ngạn, Bắc Giang",
    "ten_vuon": "Vườn Bác Hải",
    "ngay_thu_hoach": "2026-06-13",
    "lan_phun_thuoc_gan_nhat": "2026-06-07",
    "cach_ly": "Không",
    "loai": "Trái tươi xuất khẩu",
    "khoi_luong_lo_hang": 19.6,
    "khoi_luong_dong_goi": 19.2,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Rồng Việt",
    "ma_phc": "VN-PHC-0004",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "BG-009",
    "ma_puc": "BG-PUC-0009",
    "dia_chi_vuon": "Xã Phượng Sơn, H. Lục Ngạn, Bắc Giang",
    "ten_vuon": "Vườn Chị Mai",
    "ngay_thu_hoach": "2026-06-12",
    "lan_phun_thuoc_gan_nhat": "2026-06-05",
    "cach_ly": "Có",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 14,
    "khoi_luong_dong_goi": 13.2,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "BG-010",
    "ma_puc": "BG-PUC-0010",
    "dia_chi_vuon": "Xã Thanh Hải, H. Lục Ngạn, Bắc Giang",
    "ten_vuon": "Vườn Cô Hồng",
    "ngay_thu_hoach": "2026-06-24",
    "lan_phun_thuoc_gan_nhat": "2026-06-17",
    "cach_ly": "Không",
    "loai": "Trái tươi xuất khẩu",
    "khoi_luong_lo_hang": 10,
    "khoi_luong_dong_goi": 9.9,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": "VN-PHC-0009",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "BG-011",
    "ma_puc": "BG-PUC-0011",
    "dia_chi_vuon": "Xã Đồng Cốc, H. Lục Ngạn, Bắc Giang",
    "ten_vuon": "Vườn Anh Quân",
    "ngay_thu_hoach": "2026-06-22",
    "lan_phun_thuoc_gan_nhat": "2026-06-15",
    "cach_ly": "Có",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 7,
    "khoi_luong_dong_goi": 6.8,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hưng Phát",
    "ma_phc": "VN-PHC-0001",
    "ket_qua_kiem_dich": "Không đạt"
  },
  {
    "id": "HG-005",
    "ma_puc": "HG-PUC-0005",
    "dia_chi_vuon": "Xã Mỹ Đức, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Chị Thủy",
    "ngay_thu_hoach": "2026-06-12",
    "lan_phun_thuoc_gan_nhat": "2026-06-04",
    "cach_ly": "Không",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 23.5,
    "khoi_luong_dong_goi": 23.1,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Minh Sáng",
    "ma_phc": "VN-PHC-0008",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "HG-006",
    "ma_puc": "HG-PUC-0006",
    "dia_chi_vuon": "Xã Ô Long Vĩ, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Bác Hùng",
    "ngay_thu_hoach": "2026-06-20",
    "lan_phun_thuoc_gan_nhat": "2026-06-14",
    "cach_ly": "Có",
    "loai": "Trái tươi xuất khẩu",
    "khoi_luong_lo_hang": 22.3,
    "khoi_luong_dong_goi": 22.1,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hưng Phát",
    "ma_phc": "VN-PHC-0001",
    "ket_qua_kiem_dich": "Không đạt"
  },
  {
    "id": "HG-007",
    "ma_puc": "HG-PUC-0007",
    "dia_chi_vuon": "Xã Thạnh Mỹ Tây, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Chú Tư",
    "ngay_thu_hoach": "2026-06-21",
    "lan_phun_thuoc_gan_nhat": "2026-06-15",
    "cach_ly": "Không",
    "loai": "Trái tươi xuất khẩu",
    "khoi_luong_lo_hang": 10.3,
    "khoi_luong_dong_goi": 10.1,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hòa Phát",
    "ma_phc": "VN-PHC-0007",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "HG-008",
    "ma_puc": "HG-PUC-0008",
    "dia_chi_vuon": "Xã Đào Hữu Cảnh, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Anh Bình",
    "ngay_thu_hoach": "2026-06-24",
    "lan_phun_thuoc_gan_nhat": "2026-06-18",
    "cach_ly": "Có",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 19.6,
    "khoi_luong_dong_goi": 19.2,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Minh Sáng",
    "ma_phc": "VN-PHC-0008",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "HG-009",
    "ma_puc": "HG-PUC-0009",
    "dia_chi_vuon": "Xã Bình Chánh, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Cô Liên",
    "ngay_thu_hoach": "2026-06-15",
    "lan_phun_thuoc_gan_nhat": "2026-06-08",
    "cach_ly": "Không",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 10.9,
    "khoi_luong_dong_goi": 10.9,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": "VN-PHC-0009",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "HG-010",
    "ma_puc": "HG-PUC-0010",
    "dia_chi_vuon": "Xã Bình Phú, H. Châu Phú, An Giang",
    "ten_vuon": "Vườn Ông Mười",
    "ngay_thu_hoach": "2026-06-16",
    "lan_phun_thuoc_gan_nhat": "2026-06-09",
    "cach_ly": "Có",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 11.3,
    "khoi_luong_dong_goi": 10.2,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "TG-005",
    "ma_puc": "TG-PUC-0005",
    "dia_chi_vuon": "Xã Cẩm Sơn, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Chị Hằng",
    "ngay_thu_hoach": "2026-06-22",
    "lan_phun_thuoc_gan_nhat": "2026-06-14",
    "cach_ly": "Có",
    "loai": null,
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "TG-006",
    "ma_puc": "TG-PUC-0006",
    "dia_chi_vuon": "Xã Hiệp Đức, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Anh Thịnh",
    "ngay_thu_hoach": "2026-06-19",
    "lan_phun_thuoc_gan_nhat": "2026-06-11",
    "cach_ly": "Có",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 8.1,
    "khoi_luong_dong_goi": 8.1,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Sen Vàng",
    "ma_phc": "VN-PHC-0003",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "TG-007",
    "ma_puc": "TG-PUC-0007",
    "dia_chi_vuon": "Xã Tân Phong, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Bác Sáu",
    "ngay_thu_hoach": "2026-06-18",
    "lan_phun_thuoc_gan_nhat": "2026-06-11",
    "cach_ly": "Không",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 6.4,
    "khoi_luong_dong_goi": 5.8,
    "noi_xuat_khau": "Nhật Bản",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hòa Phát",
    "ma_phc": "VN-PHC-0007",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "TG-008",
    "ma_puc": "TG-PUC-0008",
    "dia_chi_vuon": "Xã Ngũ Hiệp, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Chú Út",
    "ngay_thu_hoach": "2026-06-21",
    "lan_phun_thuoc_gan_nhat": "2026-06-14",
    "cach_ly": "Có",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 22.8,
    "khoi_luong_dong_goi": 21.1,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "TG-009",
    "ma_puc": "TG-PUC-0009",
    "dia_chi_vuon": "Xã Hội Xuân, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Cô Mai",
    "ngay_thu_hoach": "2026-06-24",
    "lan_phun_thuoc_gan_nhat": "2026-06-18",
    "cach_ly": "Không",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 16.9,
    "khoi_luong_dong_goi": 16.3,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Á Đông",
    "ma_phc": "VN-PHC-0010",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "TG-010",
    "ma_puc": "TG-PUC-0010",
    "dia_chi_vuon": "Xã Long Khánh, H. Cai Lậy, Tiền Giang",
    "ten_vuon": "Vườn Anh Khánh",
    "ngay_thu_hoach": "2026-06-15",
    "lan_phun_thuoc_gan_nhat": "2026-06-09",
    "cach_ly": "Có",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 11.3,
    "khoi_luong_dong_goi": 10.5,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Mekong",
    "ma_phc": "VN-PHC-0006",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "LA-005",
    "ma_puc": "LA-PUC-0005",
    "dia_chi_vuon": "Xã Mỹ Hạnh Nam, H. Đức Hòa, Long An",
    "ten_vuon": "Vườn Chị Dung",
    "ngay_thu_hoach": "2026-06-14",
    "lan_phun_thuoc_gan_nhat": "2026-06-06",
    "cach_ly": "Không",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 12.9,
    "khoi_luong_dong_goi": 12.5,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Mekong",
    "ma_phc": "VN-PHC-0006",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "LA-006",
    "ma_puc": "LA-PUC-0006",
    "dia_chi_vuon": "Xã Hựu Thạnh, H. Đức Hòa, Long An",
    "ten_vuon": "Vườn Anh Tuấn",
    "ngay_thu_hoach": "2026-06-25",
    "lan_phun_thuoc_gan_nhat": "2026-06-17",
    "cach_ly": "Không",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 23.6,
    "khoi_luong_dong_goi": 23.4,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Á Đông",
    "ma_phc": "VN-PHC-0010",
    "ket_qua_kiem_dich": "Không đạt"
  },
  {
    "id": "LA-007",
    "ma_puc": "LA-PUC-0007",
    "dia_chi_vuon": "Xã Hòa Khánh Nam, H. Đức Hòa, Long An",
    "ten_vuon": "Vườn Bác Minh",
    "ngay_thu_hoach": "2026-06-15",
    "lan_phun_thuoc_gan_nhat": "2026-06-09",
    "cach_ly": "Có",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 24.9,
    "khoi_luong_dong_goi": 22.6,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói VinaGreen",
    "ma_phc": "VN-PHC-0005",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "LA-008",
    "ma_puc": "LA-PUC-0008",
    "dia_chi_vuon": "Xã Đức Lập Hạ, H. Đức Hòa, Long An",
    "ten_vuon": "Vườn Chú Bảy",
    "ngay_thu_hoach": "2026-06-22",
    "lan_phun_thuoc_gan_nhat": "2026-06-14",
    "cach_ly": "Không",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  },
  {
    "id": "LA-009",
    "ma_puc": "LA-PUC-0009",
    "dia_chi_vuon": "Xã Hướng Thọ Phú, TP. Tân An, Long An",
    "ten_vuon": "Vườn Cô Lan",
    "ngay_thu_hoach": "2026-06-16",
    "lan_phun_thuoc_gan_nhat": "2026-06-10",
    "cach_ly": "Có",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 12,
    "khoi_luong_dong_goi": 10.9,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói VinaGreen",
    "ma_phc": "VN-PHC-0005",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "LA-010",
    "ma_puc": "LA-PUC-0010",
    "dia_chi_vuon": "Xã Bình Thạnh, H. Thủ Thừa, Long An",
    "ten_vuon": "Vườn Anh Sơn",
    "ngay_thu_hoach": "2026-06-12",
    "lan_phun_thuoc_gan_nhat": "2026-06-06",
    "cach_ly": "Có",
    "loai": "Nguyên trái đông lạnh",
    "khoi_luong_lo_hang": 21.7,
    "khoi_luong_dong_goi": 21.1,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": "VN-PHC-0009",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "VL-004",
    "ma_puc": "VL-PUC-0004",
    "dia_chi_vuon": "Xã Trung Hiếu, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Chị Thảo",
    "ngay_thu_hoach": "2026-06-21",
    "lan_phun_thuoc_gan_nhat": "2026-06-15",
    "cach_ly": "Không",
    "loai": "Trái tươi xuất khẩu",
    "khoi_luong_lo_hang": 5.2,
    "khoi_luong_dong_goi": 5.1,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Thanh Bình",
    "ma_phc": "VN-PHC-0002",
    "ket_qua_kiem_dich": "Không đạt"
  },
  {
    "id": "VL-005",
    "ma_puc": "VL-PUC-0005",
    "dia_chi_vuon": "Xã Hiếu Thành, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Bác Lâm",
    "ngay_thu_hoach": "2026-06-17",
    "lan_phun_thuoc_gan_nhat": "2026-06-10",
    "cach_ly": "Không",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 7.7,
    "khoi_luong_dong_goi": 7,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Trường Thịnh",
    "ma_phc": "VN-PHC-0009",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "VL-006",
    "ma_puc": "VL-PUC-0006",
    "dia_chi_vuon": "Xã Trung An, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Chú Hoàng",
    "ngay_thu_hoach": "2026-06-19",
    "lan_phun_thuoc_gan_nhat": "2026-06-13",
    "cach_ly": "Có",
    "loai": "Lột múi cơm",
    "khoi_luong_lo_hang": 10.6,
    "khoi_luong_dong_goi": 9.8,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói VinaGreen",
    "ma_phc": "VN-PHC-0005",
    "ket_qua_kiem_dich": null
  },
  {
    "id": "VL-007",
    "ma_puc": "VL-PUC-0007",
    "dia_chi_vuon": "Xã Trung Thành Tây, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Cô Huệ",
    "ngay_thu_hoach": "2026-06-23",
    "lan_phun_thuoc_gan_nhat": "2026-06-15",
    "cach_ly": "Không",
    "loai": "Trái tươi xuất khẩu",
    "khoi_luong_lo_hang": 15.1,
    "khoi_luong_dong_goi": 14,
    "noi_xuat_khau": "Hàn Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Hưng Phát",
    "ma_phc": "VN-PHC-0001",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "VL-008",
    "ma_puc": "VL-PUC-0008",
    "dia_chi_vuon": "Xã Tân Quới Trung, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Anh Nam",
    "ngay_thu_hoach": "2026-06-15",
    "lan_phun_thuoc_gan_nhat": "2026-06-08",
    "cach_ly": "Có",
    "loai": "Sấy khô",
    "khoi_luong_lo_hang": 13.5,
    "khoi_luong_dong_goi": 12.5,
    "noi_xuat_khau": "Trung Quốc",
    "ten_co_so_dong_goi": "Cơ sở đóng gói Sen Vàng",
    "ma_phc": "VN-PHC-0003",
    "ket_qua_kiem_dich": "Đạt"
  },
  {
    "id": "VL-009",
    "ma_puc": "VL-PUC-0009",
    "dia_chi_vuon": "Xã Thanh Bình, H. Vũng Liêm, Vĩnh Long",
    "ten_vuon": "Vườn Chị Hương",
    "ngay_thu_hoach": "2026-06-11",
    "lan_phun_thuoc_gan_nhat": "2026-06-03",
    "cach_ly": null,
    "loai": null,
    "khoi_luong_lo_hang": null,
    "khoi_luong_dong_goi": null,
    "noi_xuat_khau": null,
    "ten_co_so_dong_goi": null,
    "ma_phc": null,
    "ket_qua_kiem_dich": null
  }
];

export const personnelData = [
  {
    "ma_nv": "NV001",
    "ten_nv": "Nguyễn Văn An"
  },
  {
    "ma_nv": "NV002",
    "ten_nv": "Trần Thị Bình"
  },
  {
    "ma_nv": "NV003",
    "ten_nv": "Lê Hoàng Chi"
  },
  {
    "ma_nv": "NV004",
    "ten_nv": "Phạm Quốc Đạt"
  },
  {
    "ma_nv": "NV005",
    "ten_nv": "Hoàng Kim Anh"
  },
  {
    "ma_nv": "NV006",
    "ten_nv": "Vũ Tiến Đức"
  },
  {
    "ma_nv": "NV007",
    "ten_nv": "Ngô Quốc Huy"
  },
  {
    "ma_nv": "NV008",
    "ten_nv": "Đỗ Minh Khang"
  },
  {
    "ma_nv": "NV009",
    "ten_nv": "Bùi Phương Linh"
  },
  {
    "ma_nv": "NV010",
    "ten_nv": "Nguyễn Tiến Dũng"
  }
];

export const customerData = [
  {
    "ma_kh": "KH001",
    "ten_kh": "Guangzhou Fruit Import & Export Co., Ltd.",
    "quoc_gia": "Trung Quốc"
  },
  {
    "ma_kh": "KH002",
    "ten_kh": "Shenzhen Fresh Trade Co.",
    "quoc_gia": "Trung Quốc"
  },
  {
    "ma_kh": "KH003",
    "ten_kh": "Shanghai Xinlian Import Co.",
    "quoc_gia": "Trung Quốc"
  },
  {
    "ma_kh": "KH004",
    "ten_kh": "Tokyo Fresh Fruits Co., Ltd.",
    "quoc_gia": "Nhật Bản"
  },
  {
    "ma_kh": "KH005",
    "ten_kh": "Seoul Mart Corporation",
    "quoc_gia": "Hàn Quốc"
  }
];
